// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjqnYPEeqUJGZDkp5XuURtzVjCBEPXkmo',
    appId: '1:988673340602:android:070a1916031df851c17e83',
    messagingSenderId: '988673340602',
    projectId: 'experimenthome-be54b',
    storageBucket: 'experimenthome-be54b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZuLnSXAw19JOhkaOTg44B4_gkw_m1ZrA',
    appId: '1:988673340602:ios:8acbb1be823fc0d9c17e83',
    messagingSenderId: '988673340602',
    projectId: 'experimenthome-be54b',
    storageBucket: 'experimenthome-be54b.firebasestorage.app',
    iosBundleId: 'com.remotelab.experimenthome',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSj4xTLni38tBBfmdgukG13X8ND6WW8Zg',
    appId: '1:988673340602:web:f923afc04028b6cdc17e83',
    messagingSenderId: '988673340602',
    projectId: 'experimenthome-be54b',
    authDomain: 'experimenthome-be54b.firebaseapp.com',
    storageBucket: 'experimenthome-be54b.firebasestorage.app',
  );
}
